mario:	mario.c
		clang	-fsanitize=integer	-fsanitize=undefined	-ggdb3	-O0	-std=c11	-Wall	-Werror	-Wextra	-Wno-sign-compare	-Wshadow	mario.c	-lcrypt	-lcs50	-lm	-o	mario

credit:	credit.c
		clang	-fsanitize=integer	-fsanitize=undefined	-ggdb3	-O0	-std=c11	-Wall	-Werror	-Wextra	-Wno-sign-compare	-Wshadow	credit.c	-lcrypt	-lcs50	-lm	-o	credit