#!/usr/bin/env python3

import sys
import helpers
import os

from analyzer import Analyzer
from termcolor import colored

# TODO
def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @handle")

    # get tweets
    tweets = helpers.get_user_timeline(sys.argv[1])
    if tweets == None:
        print("Error retrieving tweets")
        return 1

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    #initialize Analyzer
    analyzer = Analyzer(positives, negatives)

    score = 0
    # analyse tweets
    for tweet in tweets:
        score += analyzer.analyze(tweet)
    print(score)
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()