#!/usr/bin/env python3

import sys
import helpers
import os

from analyzer import Analyzer
from termcolor import colored


def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @handle")

    # get tweets
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    if tweets is None:
        print("Error retrieving tweets: User protected or does not exist.")
        return 1

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # initialize Analyzer
    analyzer = Analyzer(positives, negatives)

    score = 0
    # analyse tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)

        if score > 0.0:
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(tweet, "red"))
        else:
            print(colored(tweet, "yellow"))

if __name__ == "__main__":
    main()